### ISSUE TITLE
AdGuard suggested general lists for blocking tracking and advertising failed to install

### ISSUE THREAD

**Issue by mjhymowitz** [AdguardTeam/AdGuardHome#5417]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

Other (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

latest or v0.108.0-b.25

#### What did you do?
I tied to add all the block list under General that Adguard recommends
#### Expected result
All list will install and be added to the DNS blocklist
#### Actual result
Only AdGuard DNS filter and AdAway Default Blocklist successfully installed. The rest of the recommended blocklist failed to install. The logs say all the urls are already added, when I go to the DNS blocklists page the urls and titles the the blocklist are not listed.

```
2023-01-28 20:04:09 2023/01/28 20:04:09.117391 [error] POST localhost /control/filtering/add_url: Filter URL already added -- https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt
2023-01-28 20:04:09 2023/01/28 20:04:09.117569 [error] POST localhost /control/filtering/add_url: Filter URL already added -- https://adguardteam.github.io/HostlistsRegistry/assets/filter_38.txt
2023-01-28 20:04:09 2023/01/28 20:04:09.117766 [error] POST localhost /control/filtering/add_url: Filter URL already added -- https://adguardteam.github.io/HostlistsRegistry/assets/filter_28.txt
2023-01-28 20:04:09 2023/01/28 20:04:09.117888 [error] POST localhost /control/filtering/add_url: Filter URL already added -- https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt
2023-01-28 20:04:09 2023/01/28 20:04:09.117964 [error] POST localhost /control/filtering/add_url: Filter URL already added -- https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt
2023-01-28 20:04:09 2023/01/28 20:04:09.118009 [error] POST localhost /control/filtering/add_url: Filter URL already added -- https://adguardteam.github.io/HostlistsRegistry/assets/filter_5.txt
2023-01-28 20:04:09 2023/01/28 20:04:09.118060 [error] POST localhost /control/filtering/add_url: Filter URL already added -- https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt
2023-01-28 20:04:09 2023/01/28 20:04:09.118103 [error] POST localhost /control/filtering/add_url: Filter URL already added -- https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt
2023-01-28 20:04:09 2023/01/28 20:04:09.118146 [error] POST localhost /control/filtering/add_url: Filter URL already added -- https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
2023-01-28 20:04:09 2023/01/28 20:04:09.141630 [error] POST localhost /control/filtering/add_url: Filter URL already added -- https://adguardteam.github.io/HostlistsRegistry/assets/filter_38.txt
```

#### Screenshots (if applicable)
![logs](https://user-images.githubusercontent.com/9580326/215305036-7f38a016-a9c1-4cc4-8c48-c8563e6c4cc9.PNG)
![dns list](https://user-images.githubusercontent.com/9580326/215305037-47a7e9be-d994-48eb-9bd2-9ba70928c02c.PNG)

#### Additional information
I am running docker on a windows 10 64bit computer with wsl (windows subsystem for linux) running linux. I'm assuming AdGuardHome is running on Linux.
