### ISSUE TITLE
Docker checklist

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#562]
1. [x] Can we have a single Dockerfile for all OS/architectures?
2. [x] Official Docker image on docker hub for both releases and `latest` (built from master).
3. [x] Multi-stage build (might be necessary for the `latest` image): https://github.com/AdguardTeam/AdGuardHome/issues/514#issuecomment-450776619
4. [x] Figure out what to do with volumes
5. [x] Add installation instruction to README
